name: OpenMod.Analyzers

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Analyzers.yml'
      - 'framework/OpenMod.Analyzers/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Analyzers.yml/**'
      - 'framework/OpenMod.Analyzers/**'

jobs:
  build:
    name: "OpenMod.Analyzers Build"
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2    
    - uses: ./.github/actions/project-build
      id: project-build    
      with:
        project_path: framework/OpenMod.Analyzers
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
