name: OpenMod.Core

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - 'framework/OpenMod.Core/**'
      - 'framework/OpenMod.NuGet/**'
      - 'framework/OpenMod.API/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'framework/OpenMod.Core/**'
      - 'framework/OpenMod.NuGet/**'
      - 'framework/OpenMod.API/**'

jobs:
  build:
    name: "OpenMod.Core Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags)        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore framework/OpenMod.Core
    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ steps.get_version.outputs.VERSION }}</Version>#\" props/SharedProjectProps.props"
    - name: Build
      run: dotnet build framework/OpenMod.Core --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Push to NuGet
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: dotnet nuget push framework/OpenMod.Core/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json