name: OpenMod.Release

on:
  create:
    tags:
      - "*"
      
jobs:
  gitHubRelease:
    name: "GitHub Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags)      
    - name: Create release
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      id: create_release
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        tag: ${{ steps.get_version.outputs.VERSION }}
        name: OpenMod Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false