name: OpenMod.Extensions.Games.Abstractions

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - 'extensions/OpenMod.Extensions.Games.Abstractions/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'extensions/OpenMod.Extensions.Games.Abstractions/**'

jobs:
  build:
    name: "OpenMod.Extensions.Games.Abstractions Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags)        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore extensions/OpenMod.Extensions.Games.Abstractions
    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ steps.get_version.outputs.VERSION }}</Version>#\" props/SharedProjectProps.props"
    - name: Build
      run: dotnet build extensions/OpenMod.Extensions.Games.Abstractions --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Push to NuGet
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: dotnet nuget push extensions/OpenMod.Extensions.Games.Abstractions/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json