name: OpenMod.Rust.Oxide

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Rust.Oxide.yml'
      - 'rust/oxide/OpenMod.Rust.Oxide/**'
      - 'rust/oxide/tests/OpenMod.Rust.Oxide.Tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Rust.Oxide.yml'
      - 'rust/oxide/OpenMod.Rust.Oxide/**'
      - 'rust/oxide/tests/OpenMod.Rust.Oxide.Tests/**'

jobs:
  build:
    name: "OpenMod.Rust.Oxide Build"
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2    
    - uses: actions/setup-dotnet@v1
      name: Setup .NET
      with:
        dotnet-version: 5.0.100        
    - uses: ././.github/actions/project-build
      id: project-build    
      with:
        project_path: rust/oxide/OpenMod.Rust.Oxide
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true